spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: ${DATASOURCE_DRIVER}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}