version: '3'
services:
  ai:
    container_name: ai-container
    image: ai-env
    build:
      context: .
      dockerfile: Dockerfile
    hostname: ai_container
    ports:
      - 2223:22
    volumes:
      - .:/root
    stdin_open: true
    tty: true