name: CD

on:
  push: 
    branches:
      - master

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./back

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Build With Gradle
        run: ./gradlew build -x test
        working-directory: ${{ env.working-directory }}

      - name: Docker build & Push
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/facefriend .
          docker push ${{ secrets.DOCKER_REPO }}/facefriend
        working-directory: ${{ env.working-directory }}

      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
             docker stop facefriend
             docker rm facefriend
             sudo docker pull ${{ secrets.DOCKER_REPO }}/facefriend
             docker run -d --name facefriend -p 8080:8080 ${{ secrets.DOCKER_REPO }}/facefriend
             docker rmi -f $(docker images -f "dangling=true" -q)
